print("Hello word!")
print('Hello word!')
print('"Hello word!"')
print("Hello'\"'word!")
print("Hello'\"'word!")
print("Hello'\\'word!")
print('Hello ' + 'Nike!')
print('Hello', 'Nike!')
print('Hello', 'Nike','and Michael!')
print('Hello', 'Nike','and Michael!', sep="$$$")